### ISSUE TITLE
Navbar closes when current link is clicked

### ISSUE THREAD

**Issue by theianjones** [eggheadio/egghead-instructor-center#224] opened 2017-04-28 23:22 UTC
Steps to reproduce:
1. navigate to instructor center
2. click on the current link (in the root, it will be `Dashboard`)

Expected outcome:
Nothing to happen. The nav could possibly close and a hamburger show up like in mobile but that's a design choice.

Actual outcome: 
Nav closes with no way, besides a page refresh, to get it back again.

![](https://d3vv6lp55qjaqc.cloudfront.net/items/1y112h043i1K2f0E473e/Screen%20Recording%202017-04-28%20at%2004.21%20PM.gif?v=d49376f8)

**Comment by trevordmiller** [comment] 2017-04-28 23:32
Thanks for making an issue Ian. I know what the problem is and will take care of it next week.

**Comment by trevordmiller** [comment] 2017-04-28 23:33
The nav should only open/close on mobile

**Comment by trevordmiller** [comment] 2017-05-01 22:11
Resolved by https://github.com/eggheadio/egghead-instructor-center/pull/225

**Closed as completed** 2017-05-01 22:11 UTC
